version: '3.8'

services:

  backend:
    build: ./e-commers-app/.
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql_db:5432/ecommerce
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgresql_db
    networks:
      - my-network

  frontend:
    build: ./frontend/.
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network

  postgresql_db:
    image: postgres:15.2
    restart: always
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  postgresql_db:


networks:
  my-network:
    driver: bridge
